services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Frontend läuft jetzt auf Port 80 und wird durch Nginx ausgeliefert
    depends_on:
      - backend  # Das Frontend startet erst, wenn das Backend bereit ist

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dms
      SPRING_DATASOURCE_USERNAME: sophia
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - shared-files:/shared-files

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Standardport für RabbitMQ
      - "15672:15672" # Management UI Port
    environment:
      RABBITMQ_DEFAULT_USER: sophia
      RABBITMQ_DEFAULT_PASS: Login4rabbitMQ
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=dms
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sophia
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  ocrservice:
    build:
      context: "C:/Users/sophi/OneDrive/Desktop/Informatik/ocr"  # Absoluter Pfad zum OCR-Service-Projekt
      dockerfile: Dockerfile
    container_name: ocrservice
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - shared-files:/shared-files
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API-Port
      - "9001:9001"  # Web-UI-Port
    command: server /data --console-address ":9001"
    volumes:
      - shared-files:/data

volumes:
  shared-files:
    driver: local
  postgres_data:
  rabbitmq_data:
  minio_data:

