services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Frontend läuft jetzt auf Port 80 und wird durch Nginx ausgeliefert
    depends_on:
      - backend  # Das Frontend startet erst, wenn das Backend bereit ist

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dms
      SPRING_DATASOURCE_USERNAME: sophia
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Standardport für RabbitMQ
      - "15672:15672" # Management UI Port
    environment:
      RABBITMQ_DEFAULT_USER: sophia
      RABBITMQ_DEFAULT_PASS: Login4rabbitMQ
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=dms
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sophia
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  ocrservice:
    build:
      context: "C:/Users/sophi/OneDrive/Desktop/Informatik/ocr"  # Absoluter Pfad zum OCR-Service-Projekt
      dockerfile: Dockerfile
    container_name: ocrservice
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - shared-files:/shared-files
    restart: always

volumes:
  shared-files:
  postgres_data:
  rabbitmq_data:

