version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Frontend läuft jetzt auf Port 80 und wird durch Nginx ausgeliefert
    depends_on:
      - backend  # Das Frontend startet erst, wenn das Backend bereit ist

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dms
      SPRING_DATASOURCE_USERNAME: sophia
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=dms
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sophia
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
