services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=dms
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sophia
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  app:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dms
      SPRING_DATASOURCE_USERNAME: sophia
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx-webserver
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
    depends_on:
      - app

volumes:
  postgres_data:
