services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=dms
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sophia
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dms
      SPRING_DATASOURCE_USERNAME: sophia
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres_data:
